version: 2
updates:

  - package-ecosystem: "pip"
    directory: "/docs/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "krystofkomanec"
    labels:
      - "dependencies"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "develop"
    assignees:
      - "krystofkomanec"
    labels:
      - "dependencies"
